# Generated by Django 4.2 on 2024-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="service",
            field=models.CharField(
                choices=[("gmail", "Gmail"), ("yandex", "Yandex"), ("mail", "Mail.ru")],
                default="gmail",
                max_length=10,
            ),
        ),
    ]
